# Generated by Django 4.1.5 on 2023-03-10 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
                ('slug', models.SlugField(verbose_name='Slug Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Renkler')),
                ('slug', models.SlugField(verbose_name='Slug Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('text', models.TextField(max_length=600, verbose_name='Açıklama')),
                ('detail', models.TextField(max_length=500, verbose_name='Özellikler')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('stars', models.FloatField(default=0, verbose_name='Puan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='SizeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Beden Numarası')),
                ('stok', models.IntegerField(verbose_name='Stok sayısı')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.color', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.product', verbose_name='Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='SizeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_s', models.IntegerField(default=0, verbose_name='Small Stok')),
                ('stok_m', models.IntegerField(default=0, verbose_name='Medium Stok')),
                ('stok_l', models.IntegerField(default=0, verbose_name='Large Stok')),
                ('stok_xl', models.IntegerField(default=0, verbose_name='Xlarge Stok')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.color', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.product', verbose_name='Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.product', verbose_name='Ürün')),
                ('sizeletter', models.ManyToManyField(blank=True, to='appMy.sizeletter', verbose_name='Kıyafet beden ve stok')),
                ('sizenumber', models.ManyToManyField(blank=True, to='appMy.sizenumber', verbose_name='Ayyakkabı beden ve stok')),
            ],
        ),
    ]
