# Generated by Django 4.1.5 on 2023-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_productstok_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True, verbose_name='Ortalama Fiyat'),
        ),
    ]
