# Generated by Django 4.1.5 on 2023-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_card_active_alter_product_price_alter_product_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='brand',
            field=models.CharField(max_length=50, null=True, verbose_name='Marka'),
        ),
    ]
