# Generated by Django 4.1.5 on 2023-02-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(max_length=500, verbose_name='İçerik')),
                ('date_now', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('post_url', models.URLField(verbose_name='Url Adresi')),
                ('image1', models.FileField(upload_to='', verbose_name='Fotoğraf 1')),
                ('image2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf 2')),
                ('image3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf 3')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori')),
            ],
        ),
    ]
