# Generated by Django 4.1.5 on 2023-02-22 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Yetenek Adı')),
                ('statu', models.IntegerField(default=0, verbose_name='Yetenek Değeri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50, verbose_name='Şifre')),
                ('job', models.CharField(max_length=50, verbose_name='İş')),
                ('image', models.FileField(upload_to=None, verbose_name='Fotoğraf')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('adress', models.CharField(max_length=50, verbose_name='Adres')),
                ('status', models.ManyToManyField(to='appMy.userinfostatus', verbose_name='Yetenekler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
