# Generated by Django 4.1.5 on 2023-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_userinfostatus_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('title', models.CharField(max_length=50, verbose_name='Konu')),
                ('text', models.TextField(max_length=500, verbose_name='Mesaj')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='adress',
            field=models.CharField(default='-', max_length=50, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.FileField(default='None/download.jpg', upload_to=None, verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(default='-', max_length=50, verbose_name='İş'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='-', max_length=50, verbose_name='Telefon Numarası'),
        ),
    ]
