# Generated by Django 4.1.5 on 2023-02-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sozluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(max_length=2000, verbose_name='İçerik Yazısı')),
                ('date_now', models.DateTimeField(verbose_name='Tarih')),
                ('image', models.FileField(upload_to='', verbose_name='Fotoğraf')),
            ],
        ),
    ]
